Repository acm-ucr/quant-website, pull requests merged in 2025-03, with the labels that each got.

#148 Notsmkamal/refactor code props
  src/components/board/board.tsx
  src/components/events/event.tsx
  src/components/example.tsx
  src/components/home/description.tsx
  src/components/project/project.tsx
Labels: ready for review

#147 animate homepage
  src/components/home/description.tsx
  src/components/home/techstack.tsx
Labels: ready for review

#141 Refactor navbar
  src/components/navigation.tsx
Labels: ready for review

#153 board component
  package-lock.json
  package.json
  src/components/board/board.tsx
Labels: ready for review

#154 mobile logo closes navbar
  src/components/navigation.tsx
Labels: ready for review, address comments

#157 once animation loads, no reanimation
  src/components/home/description.tsx
  src/components/home/techstack.tsx
Labels: ready for review

#160 Responsified event components
  src/components/events/event.tsx
  src/components/events/events.tsx
Labels: ready for review

#161 Animate Events Component
  src/components/events/event.tsx
  src/components/events/events.tsx
Labels: ready for review

#164 resized mobile navbar
  src/components/navigation.tsx
Labels: ready for review

#162 Add the blurred ellipses to the background
  public/background/Ellipses.svg
  src/app/layout.tsx
  src/components/home/landing.tsx
Labels: ready for review

#165 calendar styling + responsify dialog
  components.json
  package-lock.json
  package.json
  src/app/events/page.tsx
  src/app/globals.css
  src/components/events/calendar.tsx
  src/components/events/events.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/dialog.tsx
  src/lib/utils.ts
  tailwind.config.ts
Labels: ready for review, Responsive

#170 simplified code + removed redundant svgs
  public/header/chevron-left.svg
  public/header/chevron-right.svg
  src/app/error.tsx
  src/app/events/page.tsx
  src/app/not-found.tsx
  src/components/header.tsx
  src/components/home/description.tsx
  src/components/navigation.tsx
Labels: address comments

#169 added fixes
  package-lock.json
  package.json
  public/board/Avo.webp
  src/app/not-found.tsx
  src/components/footer.tsx
  src/components/header.tsx
  src/components/home/landing.tsx
  src/components/project/project.tsx
Labels: address comments
