Repository acm-ucr/quant-website, pull requests merged in 2025-02, with the labels that each got.

#30 Made the description component.
  package-lock.json
  package.json
  public/assets/chartimage.webp
  src/app/page.tsx
  src/components/home/description.tsx
Labels: ready for review

#33 Ampherost/header component
  public/header/background.svg
  public/header/left-line.svg
  public/header/right-line.svg
  src/components/example.tsx
  src/components/header.tsx
Labels: ready for review

#40 built an event, still need to add icons
  package-lock.json
  public/icons/locationIcon.svg
  public/icons/timeIcon.svg
  src/app/events/page.tsx
  src/components/events/event.tsx
Labels: ready for review

#41 Techstack Component with logos and links.
  package-lock.json
  public/techstack/flask.webp
  public/techstack/numpy.webp
  public/techstack/ocaml.webp
  public/techstack/pandas.webp
  public/techstack/python.webp
  public/techstack/stata.webp
  public/techstack/tailwind.webp
  src/app/page.tsx
  src/components/home/techstack.tsx
  src/data/techstack.ts
Labels: ready for review

#57 Responsify Footer
  src/components/footer.tsx
Labels: ready for review, Responsive

#45 Project Component
  public/projects/exampleACM.svg
  src/app/projects/page.tsx
  src/components/project/project.tsx
Labels: address comments

#61 J1munoz/404 page
  public/grid.svg
  src/app/not-found.tsx
Labels: ready for review

#66 InteractiveHeader
  src/app/page.tsx
  src/components/header.tsx
Labels: ready for review

#70 Created the board component
  src/components/board/board.tsx
Labels: ready for review

#71 small bug fix to footer
  src/components/footer.tsx
Labels: ready for review

#75 Populated Home Page
  public/assets/Analyze.webp
  src/app/page.tsx
  src/components/home/description.tsx
Labels: ready for review

#67 Responsify project component
  src/components/project/project.tsx
  tailwind.config.ts
Labels: ready for review, Responsive

#63 WinThant16/Responsify techstack
  src/components/home/techstack.tsx
Labels: ready for review

#72 changed icons to white
  src/components/events/event.tsx
Labels: ready for review

#60 added hover animation to footer
  package-lock.json
  src/app/page.tsx
  src/components/footer.tsx
  tsconfig.json
Labels: ready for review

#86 added hover animation & discord link
  src/components/footer.tsx
  src/components/navigation.tsx
Labels: ready for review

#87 Shivanink/event component
  src/components/events/event.tsx
Labels: ready for review, Responsive

#88 WinThant16/404ButtonHoverAnimation
  package-lock.json
  src/app/not-found.tsx
  tailwind.config.ts
Labels: ready for review

#90 Notsmkamal/project page
  src/app/projects/page.tsx
  src/components/project/project.tsx
  src/data/project.ts
Labels: ready for review

#91 Created the boards component and board data file. Changed the image prop to utilize StaticImage located in the board file.
  public/board/PersonImage.svg
  src/components/board/board.tsx
  src/components/board/boards.tsx
  src/data/Board.ts
Labels: ready for review

#74 events
  package-lock.json
  src/app/events/page.tsx
  src/components/events/events.tsx
Labels: ready for review

#73 Ampherost/PopulateHeaders
  public/header/chevron-left
  public/header/chevron-left.svg
  public/header/chevron-right
  public/header/chevron-right.svg
  src/app/board/page.tsx
  src/app/page.tsx
  src/app/projects/page.tsx
  src/components/header.tsx
Labels: ready for review

#119 Board animated
  package-lock.json
  package.json
  src/app/board/page.tsx
Labels: ready for review

#118 changed fonts in events component
  src/components/events/events.tsx
Labels: ready for review

#116 added links to footer
  src/components/footer.tsx
  src/data/Footer.ts
Labels: ready for review

#120 WinThant16/ResponsifyBoardIpad
  src/components/board/boards.tsx
  src/data/techstack.ts
Labels: ready for review, Responsive

#115 Responsified the description component
  src/components/home/description.tsx
Labels: ready for review

#121 animate projects page + header
  src/components/header.tsx
  src/components/project/project.tsx
Labels: ready for review

#122 Changed width on ipad to match the techstack component
  src/components/home/description.tsx
Labels: ready for review

#123 Responsive event component on mobile
  public/icons/LocationIconBlue.svg
  public/icons/TimeIconMobile.svg
  public/icons/locationIcon.svg
  public/icons/timeIcon.svg
  src/components/events/event.tsx
  src/components/events/events.tsx
Labels: address comments

#125 Fix events.tsx date
  src/components/events/events.tsx
Labels: ready for review

#139 Boards fix
  src/app/board/page.tsx
  src/components/board/boards.tsx
Labels: ready for review

#138 Closed navbar on click for mobile view
  src/components/navigation.tsx
Labels: ready for review

#142 Ampherost/refactor header
  src/app/board/page.tsx
  src/app/projects/page.tsx
  src/components/header.tsx
Labels: ready for review

#146 Refactor mapping
  src/components/board/boards.tsx
  src/components/events/events.tsx
  src/components/footer.tsx
  src/components/navigation.tsx
  src/components/project/projects.tsx
Labels: ready for review

#145 Fix x overflow in boards animation
  src/app/board/page.tsx
Labels: ready for review

#144 changed animation for join us button
  package-lock.json
  package.json
  src/components/navigation.tsx
Labels: ready for review
